Quieter log messages, ignore single '-' input, exit on bad commands

diff --git a/pstate-frequency b/pstate-frequency
--- a/pstate-frequency
+++ b/pstate-frequency
@@ -168,37 +168,37 @@ check_binary()
 
 print_usage()
 {
-  log_quiet "usage:"
-  log_quiet "pstate-frequency [verbose] [ACTION] [option(s)]"
-  log_quiet
-  log_quiet "verbose:"
-  log_quiet "    unprivileged:"
-  log_quiet "    -d | --debug     Print debugging messages to stdout (multiple)"
-  log_quiet "    -q | --quiet     Supress all non-error output (multiple)"
-  log_quiet "    --color          Colorize output"
-  log_quiet
-  log_quiet
-  log_quiet "actions:"
-  log_quiet "    unprivileged:"
-  log_quiet "    -H | --help      Display this help and exit"
-  log_quiet "    -V | --version   Display application version and exit"
-  log_quiet "    -G | --get       Access current CPU values"
-  log_quiet "    --delay          Delay execution by 5 seconds"
-  log_quiet "    privileged:"
-  log_quiet "    -S | --set       Modify current CPU values"
-  log_quiet
-  log_quiet
-  log_quiet "options:"
-  log_quiet "    unprivileged:"
-  log_quiet "    -c | --current   Display the current user set CPU values"
-  log_quiet "    -r | --real      Display the real time CPU frequencies"
-  log_quiet "    privileged:"
-  log_quiet "    -p | --plan      Set a predefined power plan"
-  log_quiet "    -m | --max       Modify current CPU max frequency"
-  log_quiet "    -g | --governor  Set the cpufreq governor"
-  log_quiet "    -n | --min       Modify current CPU min frequency"
-  log_quiet "    -t | --turbo     Modify curent CPU turbo boost state"
-  log_quiet "    --sleep          Sleep before setting CPU frequencies"
+  log "usage:"
+  log "pstate-frequency [verbose] [ACTION] [option(s)]"
+  log
+  log "verbose:"
+  log "    unprivileged:"
+  log "    -d | --debug     Print debugging messages to stdout (multiple)"
+  log "    -q | --quiet     Supress all non-error output (multiple)"
+  log "    --color          Colorize output"
+  log
+  log
+  log "actions:"
+  log "    unprivileged:"
+  log "    -H | --help      Display this help and exit"
+  log "    -V | --version   Display application version and exit"
+  log "    -G | --get       Access current CPU values"
+  log "    --delay          Delay execution by 5 seconds"
+  log "    privileged:"
+  log "    -S | --set       Modify current CPU values"
+  log
+  log
+  log "options:"
+  log "    unprivileged:"
+  log "    -c | --current   Display the current user set CPU values"
+  log "    -r | --real      Display the real time CPU frequencies"
+  log "    privileged:"
+  log "    -p | --plan      Set a predefined power plan"
+  log "    -m | --max       Modify current CPU max frequency"
+  log "    -g | --governor  Set the cpufreq governor"
+  log "    -n | --min       Modify current CPU min frequency"
+  log "    -t | --turbo     Modify curent CPU turbo boost state"
+  log "    --sleep          Sleep before setting CPU frequencies"
 }
 
 print_version()
@@ -224,10 +224,13 @@ log_less_verbose()
 
 handle_argument()
 {
-  if [ -z "${option_expects_argument}" ]; then
+  if [ "$1" = '-' ]; then
+    log_all "Skip '-' processing"
+  elif [ -z "${option_expects_argument}" ]; then
     elog_verbose "option does not expect argument!"
     elog_verbose "argument: $1"
     elog_quiet "Illegal command $1"
+    exit 2
   else
     log_verbose "option: ${option_expects_argument}"
   fi
